### ISSUE TITLE
Include sample screenshot

### ISSUE THREAD

**Issue by tbm** [yurikhan/ledger-d3#2]
Can you please include a sample screenshot of the chart?  Obviously not with your data but some random data just to show the charts.

**Comment by yurikhan** [comment]
Would you like to generate some random but plausible data? Ideally, there should be several asset and expense accounts, and a few months’ worth of transactions. Also, the scripts don’t expect assets to go negative; if they do, the graph will be clipped.

**Comment by tbm** [comment]
You're asking me to do what I wanted you to do. :-P  But fair enough, I'll do a pull request. :)
